"""build_gold_set.py  (Python 3, stdlib-only)  -- H825 step 2 (ruling D11): derive the
held-out gold correction set eval.py needs for detection-level F0.5/FPR/harm metrics.

Source: corrections_draft/file_first_verified.tsv, the 122-row body-grounded triage
verdict file (H453/H825's own IRR subject). It was produced by judging each candidate
against the dictionary's *own entry text*, independently of how the detectors/ suite
generates candidates -- so it is a legitimate held-out set for detection metrics, not
data the detectors were tuned against.

Split by verdict, per the taxonomy in file_first_verified.tsv's own header comment:
  POSITIVE  (should be corrected)   -- PASS, SCAN-FIRST   (fileable typos)
  HARM      (should NOT be "fixed") -- EDITORIAL, DNF, DROP (duplicate/apparatus
            collisions, do-not-file spellings, stale) -- a detector proposing to
            change one of these damages a correct-or-non-mechanical entry; that is
            exactly the do-not-file variant-vs-typo case ruling D11 names.

Output: detectors/gold_corrections.tsv  (row_id, dict, wrong, right, class, verdict)
Usage:  python detectors/build_gold_set.py
"""
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, 'corrections_draft', 'file_first_verified.tsv')
OUT = os.path.join(HERE, 'gold_corrections.tsv')

POSITIVE_VERDICTS = {'PASS', 'SCAN-FIRST'}
HARM_VERDICTS = {'EDITORIAL', 'DNF', 'DROP'}


def main():
    rows = []
    with open(SRC, encoding='utf-8') as f:
        for line in f:
            if line.startswith('#') or not line.strip():
                continue
            p = line.rstrip('\n').split('\t')
            if p[0] == 'dict':
                continue
            rows.append({'dict': p[0], 'wrong': p[1], 'right': p[2], 'verdict': p[3]})

    lines = [
        '# gold_corrections.tsv -- held-out detection-level gold set (H825, ruling D11)',
        '# Generated by detectors/build_gold_set.py from corrections_draft/file_first_verified.tsv.',
        '# class=POSITIVE (PASS/SCAN-FIRST): a genuine fileable typo -- detectors should flag `wrong`.',
        '# class=HARM (EDITORIAL/DNF/DROP): NOT a plain typo -- flagging/"correcting" `wrong` here is',
        '#   the harm case (duplicate/apparatus collision, do-not-file spelling, or already-stale).',
        'row_id\tdict\twrong\tright\tclass\tverdict',
    ]
    n_pos = n_harm = 0
    for i, r in enumerate(rows, 1):
        if r['verdict'] in POSITIVE_VERDICTS:
            cls = 'POSITIVE'
            n_pos += 1
        elif r['verdict'] in HARM_VERDICTS:
            cls = 'HARM'
            n_harm += 1
        else:
            raise ValueError('unknown verdict %r on row %d' % (r['verdict'], i))
        lines.append('%03d\t%s\t%s\t%s\t%s\t%s' % (
            i, r['dict'], r['wrong'], r['right'], cls, r['verdict']))

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print('n=%d  POSITIVE=%d  HARM=%d  -> %s' % (len(rows), n_pos, n_harm, OUT))


if __name__ == '__main__':
    main()
