"""build_gold_set.py  (Python 3, stdlib-only)  -- H825 step 2 (ruling D11): derive the
held-out gold correction set eval.py needs for detection-level F0.5/FPR/harm metrics.

Source: corrections_draft/file_first_verified.tsv, the body-grounded triage verdict
file (H453/H825's own IRR subject). It was produced by judging each candidate
against the dictionary's *own entry text*, independently of how the detectors/ suite
generates candidates -- so it is a legitimate held-out set for detection metrics, not
data the detectors were tuned against.

Split by verdict, per the taxonomy in file_first_verified.tsv's own header comment:
  POSITIVE  (should be corrected)   -- PASS, SCAN-FIRST   (fileable typos)
  HARM      (should NOT be "fixed") -- EDITORIAL, DNF, DROP (duplicate/apparatus
            collisions, do-not-file spellings, stale) -- a detector proposing to
            change one of these damages a correct-or-non-mechanical entry; that is
            exactly the do-not-file variant-vs-typo case ruling D11 names.

Published frame: the A44 paper's figures (109 POSITIVE rows / 108 unique -- one
duplicate jAmbabat pair across SHS and WIL / 13 HARM) are frozen to the
2026-07-02 verification pass. The live TSV has since grown past that frame, so
by default this script rebuilds the gold set from the PUBLISHED frame of record
(detectors/gold_corrections.tsv row keys) and verifies it reproduces that file
exactly -- a regression gate, not a re-derivation. Use --live to build from every
row of the live TSV instead (the output then exceeds the published frame and must
not be quoted as the paper's gold set).

Output: detectors/gold_corrections.tsv  (row_id, dict, wrong, right, class, verdict)
Usage:  python detectors/build_gold_set.py            # published frame + verify
        python detectors/build_gold_set.py --live     # full live TSV (drifts)
"""
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, 'corrections_draft', 'file_first_verified.tsv')
OUT = os.path.join(HERE, 'gold_corrections.tsv')

POSITIVE_VERDICTS = {'PASS', 'SCAN-FIRST'}
HARM_VERDICTS = {'EDITORIAL', 'DNF', 'DROP'}


def read_source():
    rows = []
    with open(SRC, encoding='utf-8') as f:
        for line in f:
            if line.startswith('#') or not line.strip():
                continue
            p = line.rstrip('\n').split('\t')
            if p[0] == 'dict':
                continue
            rows.append({'dict': p[0], 'wrong': p[1], 'right': p[2], 'verdict': p[3]})
    return rows


def read_published_frame():
    keys = []
    with open(OUT, encoding='utf-8') as f:
        for line in f:
            if line.startswith('#') or not line.strip():
                continue
            p = line.rstrip('\n').split('\t')
            if p[0] == 'row_id':
                continue
            keys.append((p[1], p[2], p[3]))
    return keys


def classify(rows):
    lines = [
        '# gold_corrections.tsv -- held-out detection-level gold set (H825, ruling D11)',
        '# Generated by detectors/build_gold_set.py from corrections_draft/file_first_verified.tsv.',
        '# class=POSITIVE (PASS/SCAN-FIRST): a genuine fileable typo -- detectors should flag `wrong`.',
        '# class=HARM (EDITORIAL/DNF/DROP): NOT a plain typo -- flagging/"correcting" `wrong` here is',
        '#   the harm case (duplicate/apparatus collision, do-not-file spelling, or already-stale).',
        'row_id\tdict\twrong\tright\tclass\tverdict',
    ]
    n_pos = n_harm = 0
    for i, r in enumerate(rows, 1):
        if r['verdict'] in POSITIVE_VERDICTS:
            cls = 'POSITIVE'
            n_pos += 1
        elif r['verdict'] in HARM_VERDICTS:
            cls = 'HARM'
            n_harm += 1
        else:
            raise ValueError('unknown verdict %r on row %d' % (r['verdict'], i))
        lines.append('%03d\t%s\t%s\t%s\t%s\t%s' % (
            i, r['dict'], r['wrong'], r['right'], cls, r['verdict']))
    return lines, n_pos, n_harm


def main():
    live = '--live' in sys.argv[1:]
    src_rows = read_source()
    if live:
        rows = src_rows
    else:
        by_key = {(r['dict'], r['wrong'], r['right']): r for r in src_rows}
        frame = read_published_frame()
        rows = []
        missing = [k for k in frame if k not in by_key]
        if missing:
            sys.exit('published-frame rows missing from the live TSV (source drift): %r'
                     % missing[:5])
        rows = [by_key[k] for k in frame]
    lines, n_pos, n_harm = classify(rows)

    if live:
        print('LIVE frame: n=%d  POSITIVE=%d  HARM=%d  -- exceeds the published '
              '109/13 frame; do not quote as the A44 gold set' % (len(rows), n_pos, n_harm))
        print('writing would overwrite the published %s -- refusing without --live-write'
              % OUT)
        return

    current = open(OUT, encoding='utf-8').read()
    rebuilt = '\n'.join(lines) + '\n'
    if current == rebuilt:
        print('n=%d  POSITIVE=%d  HARM=%d  -> %s  (matches published gold; frame OK)'
              % (len(rows), n_pos, n_harm, OUT))
    else:
        sys.exit('rebuilt gold set DIFFERS from the committed %s -- inspect before '
                 'overwriting (verdict drift in the source TSV?)' % OUT)


if __name__ == '__main__':
    main()
