"""irr_agreement.py  (Python 3, stdlib-only)  -- H453 step 3: Cohen's kappa, exact.

Computes inter-annotator agreement between the committed FILE-FIRST verdicts
(corrections_draft/file_first_verified.tsv, annotator A) and the blind second
annotation (corrections_draft/irr/second_annotations.tsv, annotator B) over the
five-way taxonomy PASS / SCAN-FIRST / EDITORIAL / DNF / DROP.

All arithmetic is exact (fractions.Fraction) -- no scipy, no float approximations
(the A37 lesson: scipy's t-approximation was invalid at small n; see
exact_spearman_p() in detectors/drift_dating.py). Decimals shown are exact
fractions rendered to 4 places.

Outputs:
  corrections_draft/irr/agreement_stats.md   (matrix, kappa overall + per class,
                                              percent agreement, disagreement list)
  and the same summary to stdout.

Usage: python detectors/irr_agreement.py
"""
import os
import sys
from fractions import Fraction

sys.stdout.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
A_SRC = os.path.join(ROOT, 'corrections_draft', 'file_first_verified.tsv')
B_SRC = os.path.join(ROOT, 'corrections_draft', 'irr', 'second_annotations.tsv')
OUT = os.path.join(ROOT, 'corrections_draft', 'irr', 'agreement_stats.md')

LABELS = ['PASS', 'SCAN-FIRST', 'EDITORIAL', 'DNF', 'DROP']


def read_a():
    rows = []
    with open(A_SRC, encoding='utf-8') as f:
        for line in f:
            if line.startswith('#') or not line.strip():
                continue
            p = line.rstrip('\n').split('\t')
            if p[0] == 'dict':
                continue
            rows.append({'dict': p[0], 'wrong': p[1], 'right': p[2], 'a': p[3]})
    for i, r in enumerate(rows, 1):
        r['row_id'] = '%03d' % i
    return rows


def read_b():
    out = {}
    with open(B_SRC, encoding='utf-8') as f:
        for line in f:
            if line.startswith('#') or not line.strip():
                continue
            p = line.rstrip('\n').split('\t')
            if p[0] == 'row_id':
                continue
            out[p[0]] = {'b': p[1], 'reason': p[2] if len(p) > 2 else ''}
    return out


def kappa(pairs):
    """Exact Cohen's kappa over (a,b) label pairs -> (po, pe, kappa) Fractions."""
    n = len(pairs)
    po = Fraction(sum(1 for a, b in pairs if a == b), n)
    pe = Fraction(0)
    for lab in LABELS:
        na = sum(1 for a, _ in pairs if a == lab)
        nb = sum(1 for _, b in pairs if b == lab)
        pe += Fraction(na, n) * Fraction(nb, n)
    if pe == 1:
        return po, pe, Fraction(1)
    return po, pe, (po - pe) / (1 - pe)


def binary_kappa(pairs, lab):
    """Kappa for one class vs rest."""
    bp = [(a == lab, b == lab) for a, b in pairs]
    n = len(bp)
    po = Fraction(sum(1 for a, b in bp if a == b), n)
    pe = Fraction(0)
    for v in (True, False):
        na = sum(1 for a, _ in bp if a == v)
        nb = sum(1 for _, b in bp if b == v)
        pe += Fraction(na, n) * Fraction(nb, n)
    if pe == 1:
        return Fraction(1)
    return (po - pe) / (1 - pe)


def dec(fr, places=4):
    return ('%.*f' % (places, float(fr)))


def main():
    a_rows = read_a()
    b_map = read_b()
    missing = [r['row_id'] for r in a_rows if r['row_id'] not in b_map]
    if missing:
        print('FATAL: %d rows lack a second annotation: %s' % (len(missing), missing))
        sys.exit(1)
    pairs = [(r['a'], b_map[r['row_id']]['b']) for r in a_rows]
    n = len(pairs)
    po, pe, k = kappa(pairs)

    # confusion matrix a (rows) x b (cols)
    mat = {la: {lb: 0 for lb in LABELS} for la in LABELS}
    for a, b in pairs:
        mat[a][b] += 1

    lines = []
    w = lines.append
    w('# IRR agreement statistics — FILE-FIRST verdicts vs blind second annotator')
    w('')
    w('_Generated by [detectors/irr_agreement.py](https://github.com/drdhaval2785/SanskritSpellCheck/blob/master/detectors/irr_agreement.py); exact arithmetic (fractions), n=%d._' % n)
    w('')
    w('| metric | exact | decimal |')
    w('|---|---|---|')
    w('| observed agreement p_o | %s | %s |' % (po, dec(po)))
    w('| chance agreement p_e | %s | %s |' % (pe, dec(pe)))
    w("| Cohen's kappa | %s | %s |" % (k, dec(k)))
    w('')
    w('## Confusion matrix (rows = annotator A, FILE-FIRST verdicts; cols = annotator B, blind)')
    w('')
    w('| A \\ B | ' + ' | '.join(LABELS) + ' | total |')
    w('|---|' + '---|' * (len(LABELS) + 1))
    for la in LABELS:
        row = [str(mat[la][lb]) for lb in LABELS]
        w('| **%s** | %s | %d |' % (la, ' | '.join(row), sum(mat[la].values())))
    w('| **total** | ' + ' | '.join(str(sum(mat[la][lb] for la in LABELS)) for lb in LABELS) + ' | %d |' % n)
    w('')
    w('## Per-class kappa (class vs rest)')
    w('')
    w('| class | A count | B count | binary kappa |')
    w('|---|---|---|---|')
    for lab in LABELS:
        na = sum(1 for a, _ in pairs if a == lab)
        nb = sum(1 for _, b in pairs if b == lab)
        w('| %s | %d | %d | %s |' % (lab, na, nb, dec(binary_kappa(pairs, lab))))
    w('')
    w('## Secondary statistic: binary defect-recognized collapse')
    w('')
    w('Labels collapsed to ACT = {PASS, SCAN-FIRST, EDITORIAL} (a genuine defect needing')
    w('action) vs NOACT = {DNF, DROP}. This is the pre-registered secondary view (filing')
    w('*policy* removed, defect *recognition* kept); it was not selected post hoc.')
    w('')
    bmap = lambda x: 'ACT' if x in ('PASS', 'SCAN-FIRST', 'EDITORIAL') else 'NOACT'  # noqa: E731
    bpairs = [(bmap(a), bmap(b)) for a, b in pairs]
    bn = len(bpairs)
    bpo = Fraction(sum(1 for a, b in bpairs if a == b), bn)
    bpe = Fraction(0)
    for v in ('ACT', 'NOACT'):
        na = sum(1 for a, _ in bpairs if a == v)
        nb = sum(1 for _, b in bpairs if b == v)
        bpe += Fraction(na, bn) * Fraction(nb, bn)
    bk = Fraction(1) if bpe == 1 else (bpo - bpe) / (1 - bpe)
    w('| metric | exact | decimal |')
    w('|---|---|---|')
    w('| observed agreement p_o | %s | %s |' % (bpo, dec(bpo)))
    w("| Cohen's kappa (binary) | %s | %s |" % (bk, dec(bk)))
    w('')
    w('## Disagreements')
    w('')
    w('| row | dict | wrong | right | A | B | B reason |')
    w('|---|---|---|---|---|---|---|')
    for r in a_rows:
        b = b_map[r['row_id']]
        if r['a'] != b['b']:
            w('| %s | %s | %s | %s | %s | %s | %s |' % (
                r['row_id'], r['dict'], r['wrong'], r['right'], r['a'], b['b'],
                b['reason'].replace('|', '/')))
    w('')

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print('\n'.join(lines[:20]))
    print('...')
    print('n=%d  po=%s  kappa=%s  -> %s' % (n, dec(po), dec(k), OUT))


if __name__ == '__main__':
    main()
