"""apply_scanverify_decisions.py  (Python 3, stdlib)  -- H454: fold the scan-verification
votes back into the per-dict FILE-FIRST queues.

Consumes the decisions.json exported by the review sheet
review/sanskritspellcheck-filefirst-scanverify_109rows_review.html
(generated by detectors/gen_scanverify_sheet.py; item id = "DICT:wrong:right"):

  approve -> the scanned page confirms the correction: flip the row's trailing
             ':n' to ':y' in corrections_draft/<DICT>/<DICT>_file_first_sf.txt
  reject  -> the scan shows the digitization is faithful: row stays ':n' and is
             listed for do-not-file routing (NOT auto-applied -- routing into
             the suppress list is its own reviewed step)
  defer / null -> untouched

Usage:  python corrections_draft/apply_scanverify_decisions.py <path-to-decisions.json> [--apply]
Without --apply: dry-run report only. With --apply: rewrites the queue files in place.
"""
import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    apply_mode = '--apply' in sys.argv
    if not args:
        print(__doc__)
        sys.exit(1)
    with open(args[0], encoding='utf-8') as f:
        dec = json.load(f)

    votes = {}
    for it in dec.get('items', []):
        if it.get('decision') in ('approve', 'reject'):
            d, wrong, right = it['id'].split(':', 2)
            votes[(d, wrong, right)] = (it['decision'], it.get('note', ''))

    unvoted = sum(1 for it in dec.get('items', []) if not it.get('decision'))
    print('decisions: %d approve/reject, %d defer/unvoted (sheet %s, decided %s)' % (
        len(votes), unvoted, dec.get('sheet_id'), dec.get('decided')))

    flipped, rejected, missing = 0, [], []
    by_dict = {}
    for (d, wrong, right), v in votes.items():
        by_dict.setdefault(d, []).append((wrong, right, v))

    for d, rows in sorted(by_dict.items()):
        path = os.path.join(HERE, d, '%s_file_first_sf.txt' % d)
        if not os.path.exists(path):
            missing.append(d)
            continue
        with open(path, encoding='utf-8') as f:
            lines = f.read().splitlines()
        changed = False
        for wrong, right, (decision, note) in rows:
            target = '%s:%s:%s:n' % (d, wrong, right)
            hit = False
            for i, ln in enumerate(lines):
                if ln.strip() == target:
                    hit = True
                    if decision == 'approve':
                        lines[i] = '%s:%s:%s:y' % (d, wrong, right)
                        flipped += 1
                        changed = True
                    else:
                        rejected.append((d, wrong, right, note))
                    break
            if not hit:
                # already y, commented out, or absent -- report, never guess
                missing.append(target)
        if changed and apply_mode:
            with open(path, 'w', encoding='utf-8', newline='\n') as f:
                f.write('\n'.join(lines) + '\n')
            print('  %s: written' % path)

    print('%s %d rows n->y%s' % ('FLIPPED' if apply_mode else 'would flip',
                                 flipped, '' if apply_mode else ' (dry-run; add --apply)'))
    if rejected:
        print('REJECTED on scan (stay :n; route to do-not-file via the reviewed path):')
        for d, w, r, note in rejected:
            print('  %s:%s:%s%s' % (d, w, r, ('  # ' + note) if note else ''))
    if missing:
        print('NOT FOUND (already flipped/commented/absent -- resolve by hand):')
        for m in missing:
            print('  %s' % m)


if __name__ == '__main__':
    main()
