"""multisection_error_candidates.py  (Python 3) -- H289 Phase-3 stream 1

The dictionary-headword error stream: which tier-A/B candidates from the unified
run_all suite (combined_candidates.txt) now also carry a meter= corroboration
nudge once the meter index is ENLARGED from Kāvya-only to Kāvya + the H289 sample
sections. Per the H277 invariant meter stays corroboration-only, so the actionable
subset is exactly the candidates a *second* (independent spelling) detector already
flagged AND that co-occur — DCS-rarity-gated — with a metrically non-clean verse.

Inputs (all pre-built):
  combined_candidates.txt        run_all's scored tier-A/B/C candidates (gitignored)
  meter_suspects_all.txt         meter_check.py --verdicts=meter_verdicts_all.jsonl output
  meter_verdicts.jsonl           Kāvya-only index, to attribute NEW-section contribution

Output:
  MULTISECTION_ERROR_CANDIDATES.md   ranked table + stats (committed)
  multisection_error_candidates.tsv  machine-readable, for a /review-sheet (gitignored)

  python multisection_error_candidates.py
"""
import os
import sys
import json

sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')
HERE = os.path.dirname(os.path.abspath(__file__))
DET = os.path.join(HERE, '..')


def parse_meter_suspects(path):
    """hw -> {'suspect'|'review': [loci]} from meter_check output lines
    `hw:MTR=verdict|loc;loc:DICTS` (loci themselves contain ':' via GRETIL:file)."""
    hits = {}
    with open(path, encoding='utf-8') as f:
        for line in f:
            line = line.rstrip('\n')
            if ':MTR=' not in line:
                continue
            hw, _, rest = line.partition(':MTR=')
            body, _, _dicts = rest.rpartition(':')     # dicts = after final ':' (no ':' inside)
            verdict, _, loci_str = body.partition('|')
            loci = [l for l in loci_str.split(';') if l]
            hits.setdefault(hw, {}).setdefault(verdict, []).extend(loci)
    return hits


def kavya_sources(path):
    src = set()
    if not os.path.exists(path):
        return src
    with open(path, encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line:
                src.add(json.loads(line)['source'])
    return src


def main():
    cand_path = os.path.join(DET, 'combined_candidates.txt')
    ms_path = os.path.join(HERE, 'meter_suspects_all.txt')
    hits = parse_meter_suspects(ms_path)
    kav = kavya_sources(os.path.join(HERE, 'meter_verdicts.jsonl'))

    out_rows = []
    n_ab = 0
    for line in open(cand_path, encoding='utf-8'):
        parts = line.rstrip('\n').split('\t')
        if len(parts) < 4:
            continue
        tier, score, edit, dets = parts[0], parts[1], parts[2], parts[3]
        if tier not in ('A', 'B'):
            continue
        n_ab += 1
        wrong = edit.split(' -> ')[0].strip()
        if wrong not in hits:
            continue
        verdict = 'suspect' if hits[wrong].get('suspect') else 'review'
        loci = hits[wrong].get('suspect') or hits[wrong].get('review')
        # a locus is NEW-section if its source (`GRETIL:file`) is not in the Kāvya index
        new_loci = [l for l in loci if l.split('#', 1)[0] not in kav]
        out_rows.append({
            'tier': tier, 'score': score, 'edit': edit, 'dets': dets,
            'verdict': verdict, 'n_loci': len(loci), 'n_new': len(new_loci),
            'new_only': len(new_loci) == len(loci),
            'sample_loci': loci[:4],
        })

    out_rows.sort(key=lambda r: (r['verdict'] != 'suspect', -int(r['score'])))
    n_new_only = sum(1 for r in out_rows if r['new_only'])
    n_has_new = sum(1 for r in out_rows if r['n_new'] > 0)

    # TSV (review-sheet input)
    tsv = os.path.join(HERE, 'multisection_error_candidates.tsv')
    with open(tsv, 'w', encoding='utf-8') as f:
        f.write('tier\tscore\tedit\tmeter\tdetectors\tn_loci\tn_new_section_loci\tnew_section_only\tsample_loci\n')
        for r in out_rows:
            f.write('%s\t%s\t%s\t%s\t%s\t%d\t%d\t%s\t%s\n'
                    % (r['tier'], r['score'], r['edit'], r['verdict'], r['dets'],
                       r['n_loci'], r['n_new'], r['new_only'], ';'.join(r['sample_loci'])))

    lines = []
    lines.append("# Multi-section meter-corroborated headword candidates")
    lines.append("")
    lines.append("_Auto-generated by [`multisection_error_candidates.py`](multisection_error_candidates.py). "
                 "The full ranked list is the committed `multisection_error_candidates.tsv` (the "
                 "`/review-sheet` source); this file is the summary + top rows for review._")
    lines.append("")
    lines.append("Handoff [H289](https://github.com/gasyoun/Uprava/blob/main/handoffs/"
                 "H289-Opus_SanskritSpellCheck_gretil_other_sections_pilot_07.07.26.md) Phase 3, stream 1 "
                 "(dictionary-headword corrections). A tier-A/B candidate here was flagged by ≥2 independent "
                 "spelling detectors **and** its (DCS-rare) headword co-occurs with a metrically non-clean "
                 "verse once the meter index spans Kāvya + the H289 sample sections. Meter is a "
                 "**corroboration nudge, never a tier promoter** (H277 invariant) — this list ranks, it does "
                 "not create, candidates. HUMAN-GATED: route to a `/review-sheet`, never auto-apply.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Count |")
    lines.append("|---|---:|")
    lines.append("| tier-A/B candidates scanned | %d |" % n_ab)
    lines.append("| …carrying a meter nudge (enlarged index) | %d |" % len(out_rows))
    lines.append("| …with ≥1 NEW-section (non-Kāvya) locus | %d |" % n_has_new)
    lines.append("| …corroborated ONLY by new sections | %d |" % n_new_only)
    lines.append("")
    lines.append("The **new-section-only** rows are the value the H289 expansion adds: candidates that "
                 "had no Kāvya meter corroboration and now gain one from Purāṇa / Epic / Subhāṣita / "
                 "verse-śāstra co-occurrence.")
    lines.append("")
    lines.append("## Top rows (suspect-verdict first, then by score)")
    lines.append("")
    lines.append("| Tier | Score | Edit (wrong → right) | Meter | Detectors | New-only | Sample loci |")
    lines.append("|---|---:|---|---|---|:--:|---|")
    for r in out_rows[:40]:
        loci = ', '.join(l.replace('GRETIL:', '') for l in r['sample_loci'])
        lines.append("| %s | %s | %s | %s | %s | %s | %s |"
                     % (r['tier'], r['score'], r['edit'], r['verdict'],
                        r['dets'].strip('[]'), '✓' if r['new_only'] else '', loci))
    if len(out_rows) > 40:
        lines.append("| _(%d more in the .tsv)_ | | | | | | |" % (len(out_rows) - 40))
    lines.append("")

    with open(os.path.join(HERE, 'MULTISECTION_ERROR_CANDIDATES.md'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    sys.stderr.write("multisection_error_candidates: %d tier-A/B scanned, %d meter-nudged "
                     "(%d have a new-section locus, %d new-section-only) -> MULTISECTION_ERROR_CANDIDATES.md + .tsv\n"
                     % (n_ab, len(out_rows), n_has_new, n_new_only))


if __name__ == '__main__':
    main()
