"""variety_stats.py  (Python 3) -- meter / pāda-variety census over the GRETIL index

Logs the *amount and frequency of the metrical varieties* skrutable identified across
the whole Kavya corpus -- the named meters (anuṣṭubh, upajāti triṣṭubh, āryā, vaṃśastha,
...) and, for anuṣṭubh (śloka), the per-pāda sub-variety breakdown (pathyā vs the
individual vipulās vs asamīcīnā vs the syllable-count anomalies). Per user (07-07-2026):
"I still want to know the amount and frequency of vipulā types logged, just not as
vipulā = possible typo." So this is a descriptive census of *valid* poetic variation,
computed independently of the clean/review/suspect verdict -- NOT a suspect list.

Reads meter/meter_verdicts.jsonl (all verdicts) and writes METER_VARIETY_STATS.md.

  python variety_stats.py [in=meter_verdicts.jsonl] [out=METER_VARIETY_STATS.md]
"""
import sys
import os
import re
import json
import collections

sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')
HERE = os.path.dirname(os.path.abspath(__file__))

# inside the anuṣṭubh parenthetical: "1,2: ra-vipulā; 3,4: pathyā" -> variety per pāda-pair
_SEG_RE = re.compile(r'\d[\d,\s]*:\s*([^;]+)')


def _base_meter(label):
    """Base meter name without the parenthetical/bracket variety detail. A trailing
    ' =' is skrutable's synonym-group marker (e.g. 'viyoginī =' names the same pattern
    as its synonyms) -- drop it for a clean census key."""
    return label.split(' (')[0].split(' [')[0].split(':')[0].strip().rstrip('= ').strip()


def _variety(segment):
    """First variety token of one pāda-pair segment ('ra-vipulā', 'pathyā',
    'asamīcīnā, na prathamāt snau' -> 'asamīcīnā'). '??' uncertainty kept as a tag."""
    seg = segment.strip()
    uncertain = seg.startswith('??')
    seg = seg.lstrip('? ').strip()
    name = seg.split(',')[0].split('(')[0].strip()
    return ('?? ' if uncertain else '') + name


def main(inp, out):
    base = collections.Counter()
    anu_variety = collections.Counter()
    anu_pada_pairs = 0
    n = n_anu = 0
    with open(inp, encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            label = (rec.get('skrutable') or {}).get('meter') or ''
            if not label:
                base['(no meter identified)'] += 1
                continue
            n += 1
            b = _base_meter(label)
            base[b] += 1
            if b == 'anuṣṭubh' and '(' in label:
                n_anu += 1
                inner = label[label.index('(') + 1:label.rindex(')')] if ')' in label else label[label.index('(') + 1:]
                for seg in _SEG_RE.findall(inner):
                    anu_variety[_variety(seg)] += 1
                    anu_pada_pairs += 1

    lines = []
    lines.append("# Meter / pāda-variety census — GRETIL Kavya corpus")
    lines.append("")
    lines.append("_Auto-generated by [`variety_stats.py`](variety_stats.py) from the "
                 "(gitignored, regenerable) meter index. Regenerate after a corpus rebuild._")
    lines.append("")
    lines.append("A descriptive census of the metrical varieties skrutable identified across "
                 "the corpus — **valid poetic variation, not a suspect list** (see "
                 "[`README.md`](README.md) \"Recalibration (H277)\"). Counts are per verse "
                 "(base meter) and per pāda-pair (anuṣṭubh sub-variety).")
    lines.append("")
    lines.append("## Base meter distribution (%d verses with an identified meter)" % n)
    lines.append("")
    lines.append("| Meter | Verses | Share |")
    lines.append("|---|---:|---:|")
    for name, c in base.most_common(30):
        lines.append("| %s | %d | %.1f%% |" % (name, c, 100.0 * c / n if n else 0))
    if len(base) > 30:
        lines.append("| _(%d more)_ | %d | — |"
                     % (len(base) - 30, sum(c for _, c in base.most_common()[30:])))
    lines.append("")
    lines.append("## Anuṣṭubh (śloka) pāda-variety breakdown")
    lines.append("")
    lines.append("Across **%d** anuṣṭubh verses = **%d** pāda-pairs. *pathyā* is the standard "
                 "form; the *vipulā*s and *asamīcīnā* are the recognized licensed variants; "
                 "*ūnākṣarā*/*adhikākṣarā* are syllable-count anomalies (often a prose "
                 "intrusion or a long compound, per the H277 hand-check — now largely removed "
                 "by the walker's prose-prefix strip)." % (n_anu, anu_pada_pairs))
    lines.append("")
    lines.append("| Pāda variety | Pāda-pairs | Share |")
    lines.append("|---|---:|---:|")
    for name, c in anu_variety.most_common():
        lines.append("| %s | %d | %.1f%% |" % (name, c, 100.0 * c / anu_pada_pairs if anu_pada_pairs else 0))
    lines.append("")

    with open(out, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    sys.stderr.write("variety_stats: %d verses, %d base meters, %d anuṣṭubh pāda-pairs -> %s\n"
                     % (n, len(base), anu_pada_pairs, out))


if __name__ == '__main__':
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    inp = args[0] if len(args) > 0 else os.path.join(HERE, 'meter_verdicts.jsonl')
    out = args[1] if len(args) > 1 else os.path.join(HERE, 'METER_VARIETY_STATS.md')
    main(inp, out)
